export default {
	QuicksandBold: 'Quicksand-Bold',
	QuicksandLight: 'Quicksand-Light',
	QuicksandMedium: 'Quicksand-Medium',
	QuicksandRegular: 'Quicksand-Regular',
	QuicksandSemiBold: 'Quicksand-SemiBold',
	RobotoBlack: 'Roboto-Black',
	RobotoBlackItalic: 'Roboto-BlackItalic',
	RobotoBold: 'Roboto-Bold',
	RobotoBoldItalic: 'Roboto-BoldItalic',
	RobotoItalic: 'Roboto-Italic',
	RobotoLight: 'Roboto-Light',
	RobotoLightItalic: 'Roboto-LightItalic',
	RobotoMedium: 'Roboto-Medium',
	RobotoMediumItalic: 'Roboto-MediumItalic',
	RobotoRegular: 'Roboto-Regular',
	RobotoThin: 'Roboto-Thin',
	RobotoThinItalic: 'Roboto-ThinItalic',
	MontserratBold: 'Montserrat-Bold',
	MontserratLight: 'Montserrat-Light',
	MontserratRegular: 'Montserrat-Regular',
	MontserratSemiBold: 'Montserrat-SemiBold',
};